blank_issues_enabled: true
contact_links:
  - name: Tennessee Division of Forestry
    url: https://www.tn.gov/agriculture/forests.html
    about: General information about Tennessee forestry programs and services.
